### ISSUE TITLE
Update README -- No longer an installation "the Amber way"

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/grunt-init-amber#36]
``grunt-init-amber`` does not need to be installed directly by the user at all.

Update READE.me to reflect this more **clearly**. 

Simply state

``grunt-init-amber`` is a component which is automatically installed when you install ``amber-cli``.

And then refer to the main amber installation [README](https://github.com/amber-smalltalk/amber/blob/master/README.md).

@herby : you can assign this to me.

**Comment by herby** [comment]
@mkroehnert wanted to keep it clear that this is just another grunt-init template module, usable as prescribed in grunt-init's guides. Integration to `amber init` came later.

But of course, if README is confusing, it can be refactored,

**Comment by hhzl** [comment]
My main point is that the README should state that if you are using amber-cli then you do not need to deal with this component directly.

No Amber installation instructions in this module, instead a reference should be given to the Amber main [README](https://github.com/amber-smalltalk/amber/blob/master/README.md). This will reduce Amber instructions maintenance efforts.


But what it should state how you can _use_ the module if what you want to do is going beyond using the predefined setup and starting to contribute to the development of the template or customize the template for your own purposes. This is probably a different issue.

**Comment by mkroehnert** [comment]
@hhzl I am not sure if I understand the issue completely. The README is already written in the way you describe in your second comment (except referring to the main Amber README file for installation instructions).

However, I think that I will update the file to make the intentions behind it even clearer.

**Comment by hhzl** [comment]
Yes, thank you for the update so far. It clear now. Before it was not. It was presented as an alternative which it is not in most cases.

**Comment by mkroehnert** [comment]
The other way is the alternative way (and the standard way of using
`grunt-init` templates).

It is just more convenient to have `amber init` do all the additional setup
steps required.

**Comment by hhzl** [comment]
To clarify what I meant. 

Instead of two equally valid choices we have a situation where the Amber way is the one to go for in most cases.

The README makes this clear now.

**Comment by hhzl** [comment]
Actually please close after merging.

**Comment by hhzl** [comment]
And the keywords ``gruntplugin``, ``generator`` and `` smalltalk`` might be added to the entry https://www.npmjs.com/package/grunt-init-amber. BTW pretty interesting there were 140 downloads last week. A motivation to streamline the documentatiom.
