### ISSUE TITLE
Add uninstallation instructions for "batteries included"

### ISSUE THREAD

**Issue by herby** [amber-smalltalk/grunt-init-amber#38]
The templates comes with `Web`, `Wrappers-JQuery` (and jQuery itself), `IDE`, `Benchmark` and `Examples` included. If #35 is included, it can include Silk as well.

All of those are in for the initial project to allow some preexisting code and possibilities, but in the end some of them should be ultimately uninstalled after the author chooses what to pick.

There should be uninstallation instructions included somewhere.

**Comment by hhzl** [comment]
Yes, we need uninstallation instructions.

     bower uninstall componentName
     grunt devel

... ?

**Comment by herby** [comment]
Hannes Hirzel wrote:
> Yes, we need uninstallation instructions.
>
> |  bower uninstall componentName
>   grunt devel
> |

That's hard because of possibly hanging dependencies.

Since afaik bower does not have recursive uninstall (maybe it already has in 1.4?), cleaner (but hackier) way is
|
  rm -r bower_component
  #edit out the specific line in bower.json
  bower install
|

**Comment by hhzl** [comment]
OK, then better not install it in the first place.

On the other side the hackier way is not bad though. It is easy to
understand and for reinstallation everything will just come back from
the bower cache.

**Comment by herby** [comment]
Hannes Hirzel wrote:
> OK, then better not install it in the first place.

Other pieces are the same. They are already external (Web, jQuery wrapper), so no difference here. If user chooses not to have, he must uninstall anyway.

So you mean it is better not to install even Web and jQuery wrapper?

(and not to include Examples and Benchfib in devel?)

OTOH I think things should be included in the initial project.

>
> On the other side the hackier way is not bad though. It is easy to
> understand and for reinstallation everything will just come back from
> the bower cache.
>
> On 4/19/15, Herbert Vojčík <notifications@github.com> wrote:
> > Hannes Hirzel wrote:
> >> Yes, we need uninstallation instructions.
> >>
> >> | bower uninstall componentName
> >> grunt devel
> >> |
> >
> > That's hard because of possibly hanging dependencies.
> >
> > Since afaik bower does not have recursive uninstall (maybe it 
> already has in
> > 1.4?), cleaner (but hackier) way is
> > |
> > rm 
-r bower_component

**Comment by herby** [comment]
Hannes Hirzel wrote:
> OK, then better not install it in the first place.
>
> On the other side the hackier way is not bad though. It is easy to
> understand and for reinstallation everything will just come back from
> the bower cache.
>
> On 4/19/15, Herbert Vojčík <notifications@github.com> wrote:
> > Hannes Hirzel wrote:
> >> Yes, we need uninstallation instructions.
> >>
> >> | bower uninstall componentName
> >> grunt devel
> >> |
> >
> > That's hard because of possibly hanging dependencies.
> >
> > Since afaik bower does not have recursive uninstall (maybe it 
> already has in
> > 1.4?), cleaner (but hackier) way is
> > |
> > rm -r bower_component
> > #edit out the specific line in bower.json
> > bower install
> > |


BTW, there's a less hackish way which could probably win:
|
bower uninstall componentName --save
rm -r bower_component
bower install
|

> >
> >>
> >> ... ?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> 
> <https://github.com/
amber-smalltalk/grunt-init-amber/issues/38#issuecomment-94303520>.

**Comment by hhzl** [comment]
bower uninstall componentName --save
      rm -r bower_component

Is very fine.

No need to tamper with bower.json directly.
