### ISSUE TITLE
fallback not supported in optimizer

### ISSUE THREAD

**Issue by blakemcbride** [amber-smalltalk/grunt-init-amber#40]
I had an old version of amber installed but now I did:

$ sudo npm install -g amber-cli
....
$ mkdir myapp
$ cd myapp
$ amber init
...
requirejs@2.1.20 node_modules/requirejs

amber-dev@0.7.1 node_modules/amber-dev
├── amdefine@1.0.0
├── requirejs-text@2.0.12
├── es6-promise@2.3.0
└── amd-config-builder@0.2.0 (findit@1.2.0, lodash@2.4.2)

grunt@0.4.5 node_modules/grunt
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── hooker@0.2.3
├── exit@0.1.2
├── lodash@0.9.2
├── nopt@1.0.10 (abbrev@1.0.7)
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.5)
├── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)
Running "amdconfig:app" (amdconfig) task

Running "amberc:all" (amberc) task
Reading: src/Myprog.st
Reading: src/Myprog-Tests.st

Running "amdconfig:app" (amdconfig) task

Running "requirejs:devel" (requirejs) task
{ [Error: Error: paths fallback not supported in optimizer. Please provide a build config path override for jquery
    at /home/blake/amber/node_modules/requirejs/bin/r.js:29521:23
]
  originalError: [Error: paths fallback not supported in optimizer. Please provide a build config path override for jquery] }
grunt exec error:
1
$

**Comment by herby** [comment]
When tested, happened to me as well. OTOH, I just reran the `grunt devel` from cli (the thing which `amber init` runs itself) and it worked. So some strange kind of race condition or what - paths fallback should not appear in config.js at all, as it is taken care of in amdconfig grunt task.

It would be nice if others acknowledged if they have this problem as well.

**Comment by herby** [comment]
Relocated to amber-smalltalk/amber#1198, as this is not problem of `amber init` per se.
